
export const initialStateForEnquiry = {
  enquiry_no: '',
  enquiry_date: new Date().toISOString(),
  type: ['Trade', 'Contract'],
  enquiry_by: [ 'phone' ],
  branch: 'Head Office',
  status: 'Lead In',
  by: 'User',
  estimator: '',
  sales_representative: 'Admin',
  project_name: 'Proj-1',
  architect_name: '',
  site_reference: 'holbox.ai',
  tentative_project_value: '12',
  notes: 'IIM Ahmedabad',
  customer: 'Holbox',
  contact_name: 'dhruv',
  customer_email: 'dhruv@holbox.ai',
  mobile_no: '0987654321',
  phone_no: '0987654321',
  address: 'IIM Ahmedabad',
  country: 'India',
  post_code: '120012',
  delivery_address: 'IIM Ahmedabad',
  billing_address: 'IIM Ahmedabad'
};